#!/bin/bash
# Copyright (C) 2019 Checkmk GmbH - License: Checkmk Enterprise License
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

ARCHITECTURE=i386 BITNESS_SUFFIX=-32 "$(dirname "${BASH_SOURCE[0]}")/make-agent-updater" "$@"
